version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
  build:
    commands:
      - echo "Running light syntax checks and installation validations..."
      - cd application-code/app-tier && npm install
      # If you have tests configured in your package.json, uncomment the line below:
      # - npm test